### ISSUE TITLE
prototype

### ISSUE THREAD

**Issue by tj** [gkatsev/set.js#2]
why are the methods not on the prototype? it's pretty reasonable to think that someone might create a lot of sets

**Comment by gkatsev** [comment]
Originally, I thought to keep the internal variable that holds the set private. There's a fork by Munter that I plan on pulling in that does move the functions to prototype.

**Comment by tj** [comment]
ah ok cool

**Comment by gkatsev** [comment]
Fixed in 2dc37b01c6
