### ISSUE TITLE
Would be nice to update docs to say SimpleSet or Set<Number or String>

### ISSUE THREAD

**Issue by miketheprogrammer** [gkatsev/set.js#4]
This Set implementation does not work for objects. It only works for simple immutable types such as string/int  and boxed doubles.

**Comment by gkatsev** [comment]
Yes, you're right. The keys have to be strings. I've been planning to get this to be backed by the new `Set` that's coming in ES6 but haven't had the time yet.

**Comment by miketheprogrammer** [comment]
Im currently working on a Set implementation as well, if its good maybe ill submit a pull request and we can add it as a ComplexSet attr on Set

ES6 backing would be a poor choice, considering npm is used alot with browserify to make modules frontend compatible.

However if the environment is Node, es6 set is a perfect choice, but anyone whos using es6 alread has access to that object.

Anyway, very nice module indeed sir.

**Comment by gkatsev** [comment]
I'd love a pull request. What I meant is that it'll use Set if available. If not, it'll keep doing what it's doing right now.

**Comment by miketheprogrammer** [comment]
Closing this.

**Comment by miketheprogrammer** [comment]
Grrr, apparently the ES6 Set spec is just a key based Set, no values. It underlying representation is a Map however. The Map supports the ability to do a true Set.
A true set should be of the type
Set <int,string,someotherobject> 
or
Set<v8::value>.  

Where something like var obj = {name:'michael', hash: 'asda82812'}
set.add(obj) // if isObject(obj) this.has(obj.hash) return false

or less performant would be 
set.add(obj) // if object set.has(JSON.stringify(obj));

What the hell are the leaders of javascript doing.

**Comment by gkatsev** [comment]
A `Map` has both keys and associated values. ES6 is getting both.

**Comment by miketheprogrammer** [comment]
Yes I know. I just don't get why the ES6 Implementation of Set is so simplistic, in a dynamic language.

The map object is great. Well spec'd and no complaints

**Comment by gkatsev** [comment]
I'm not sure what you mean. ES6's Set is fine. It accepts any value.

**Comment by miketheprogrammer** [comment]
Oh True. Sorry burnt out from SOAP api's all day. Your right. It does support all objects.
objects however must be the exact same instance, not just a similar object. So people hoping to use Sets to remove duplication are out of luck.
{key:1} is {key:1} // false
a = {key:1}
b = a
 a is b // true

**Comment by gkatsev** [comment]
Yes, they must be the exact same instance. But that's a limitation of js in general and not Set itself.
That's why I have the `find` (soon to be renamed `filter`) method here.

Another thing I'm considering is using ES6's proxy to proxy these methods into the Set object itself but seems like v8's proxy implementation is way out of spec, so, I'll just swap out the pojo for a `Set` if available.

**Comment by miketheprogrammer** [comment]
Yea V8's current implementation is almost completely off spec except for has/add

**Comment by gkatsev** [comment]
I just added the ability to jsonify incoming object items in #10 , so, this should adress some of the concerns in this issue.

**Comment by gkatsev** [comment]
Also, I added a note to the README.
