### ISSUE TITLE
Add a comparator for the equality check

### ISSUE THREAD

**Issue by ghost** [gkatsev/set.js#5]
Sometimes uniqueness for some items is defined by certain attributes.

The ability to give a specific comparator function would be great.
e.g

``` javascript
set = new Set()
set.comparator = function(left,right){
    left.name == right.name
}

set.add(new User("Cormac"))
set.add(new User("Cormac"))
set.get() // [ {name: "Cormac"} ]
```

**Comment by gkatsev** [comment]
Fixed in a different way in #10. We're now relying on the JSON representation of objects for the comparison.
